apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dev
            clusterServer: https://kubernetes.default.svc
            namespace: monitoring-dev
            valuesPath: applications/dev/monitoring/kube-prometheus-stack-values.yaml

          # Add prod later if you want
          # - name: prod
          #   clusterServer: https://PROD_CLUSTER_API_SERVER
          #   namespace: monitoring-prod
          #   valuesPath: applications/prod/monitoring/kube-prometheus-stack-values.yaml

  template:
    metadata:
      name: kube-prometheus-stack-{{ .name }}
    spec:
      project: default

      destination:
        server: '{{ .clusterServer }}'
        namespace: '{{ .namespace }}'

      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: "79.8.0"
          helm:
            valueFiles:
              - $values/{{ .valuesPath }}

        - repoURL: https://github.com/meshachdamilare/eduhub-apps-gitops.git
          targetRevision: main
          ref: values

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
