apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This tells Kustomize: "Use this Helm chart as a source"
helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io/
    version: 1.1.0
    releaseName: external-secrets
    namespace: external-secrets-dev   # can also be left for Argo destination control
    valuesFile: values-dev.yaml  