apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io/
    version: 1.1.0
    releaseName: external-secrets
    namespace: external-secrets-dev
    valuesFile: values-dev.yaml
